# Generated by Django 3.1 on 2021-01-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210121_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
