# Generated by Django 3.1 on 2021-01-21 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Poll Name')),
                ('text', models.TextField(max_length=300, verbose_name='Description')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 17, 21, 4, 970090, tzinfo=utc))),
                ('option1', models.TextField(max_length=500, verbose_name='Option 1')),
                ('option2', models.TextField(max_length=500, verbose_name='Option 2')),
                ('option3', models.TextField(max_length=500, verbose_name='Option 3')),
                ('option4', models.TextField(max_length=500, verbose_name='Option 4')),
                ('is_anon', models.BooleanField(default=False, verbose_name='Anonymous Poll')),
                ('count1', models.PositiveIntegerField(default=0)),
                ('count2', models.PositiveIntegerField(default=0)),
                ('count3', models.PositiveIntegerField(default=0)),
                ('count4', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
