# Generated by Django 3.1 on 2021-01-24 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 8, 25, 34, 792062, tzinfo=utc)),
        ),
    ]
