# Generated by Django 3.1 on 2021-01-24 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210124_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 12, 7, 14, 426493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_anon',
            field=models.BooleanField(default=False, verbose_name='Anonymous Poll?'),
        ),
    ]
