# Generated by Django 3.1 on 2021-01-25 04:21

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210124_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 4, 21, 6, 96893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
