# Generated by Django 3.1 on 2021-01-25 07:32

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210125_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 7, 32, 51, 485424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
    ]
