# Generated by Django 3.1 on 2021-02-02 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210125_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 14, 4, 18, 902352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_anon',
            field=models.BooleanField(default=False, verbose_name='Anonymous Poll (Author will be hidden)'),
        ),
    ]
