# Generated by Django 3.1 on 2021-01-25 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210125_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 9, 14, 34, 403738, tzinfo=utc)),
        ),
    ]
