# Generated by Django 3.1 on 2021-01-27 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210125_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 5, 26, 26, 902584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_anon',
            field=models.BooleanField(default=False, verbose_name='Anonymous Poll (Author will be hidden)'),
        ),
    ]
